// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using prosystask1.Models;

namespace prosystask1.Migrations
{
    [DbContext(typeof(TaskContext))]
    [Migration("20210628100847_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("prosystask1.Models.Course", b =>
                {
                    b.Property<string>("code")
                        .HasColumnType("char(3)");

                    b.Property<decimal>("Form")
                        .HasColumnType("decimal(2,0)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TeacherName")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TeacherSurname")
                        .HasColumnType("varchar(20)");

                    b.HasKey("code");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("prosystask1.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Courseid")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2(7)");

                    b.Property<decimal>("Grade")
                        .HasColumnType("decimal(1,0)");

                    b.Property<decimal>("Studentid")
                        .HasColumnType("decimal(5,0)");

                    b.HasKey("Id");

                    b.HasIndex("Courseid");

                    b.HasIndex("Studentid");

                    b.ToTable("Exam");
                });

            modelBuilder.Entity("prosystask1.Models.Student", b =>
                {
                    b.Property<decimal>("StudentId")
                        .HasColumnType("decimal(5,0)");

                    b.Property<decimal>("Form")
                        .HasColumnType("decimal(2,0)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Surname")
                        .HasColumnType("varchar(30)");

                    b.HasKey("StudentId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("prosystask1.Models.Exam", b =>
                {
                    b.HasOne("prosystask1.Models.Course", "Course")
                        .WithMany("Exams")
                        .HasForeignKey("Courseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("prosystask1.Models.Student", "Student")
                        .WithMany("Exams")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
